### ISSUE TITLE
Add a Paragraph of your choosing

### ISSUE THREAD

**Issue by lpeteet** [lpeteet/Collaboration-1#1]
Please add a Paragraph to index.html with text of your choosing.

Thanks!

LarryP

**Comment by lpeteet** [comment]
@MelanieWest:
Sorry for the lengthy Novel here and thanks for helping me get some practice in on this since my partner (desk mate) wasn't in class today.

This issue still says Open but it doesn't show anyone assigned.  Maybe because you closed it and now I have to do the same?  Not sure.

Did you close this issue?

Can you close it if you have not?  Or do I need to close it since I created it?
If you close it then when I get notification of that then I will create a Pull Request to Merge your branch into my Master (I think).

Also I don't think your temp branch has been merged yet as you may know.

Also can you add a comment on this just so we have a record and also gives us more practice working with this stuff?

Respectfully,

LarryP

**Comment by MelanieWest** [comment]
I closed it, I think.  Hope it worked.

I’ll try again to send the change.  I added one more change, an image.  They’ve both been pushed to origin, which should be accessible to you, but I’ll try again.

MW


Sent from Mail for Windows 10
