### ISSUE TITLE
Add CSS

### ISSUE THREAD

**Issue by MelanieWest** [lpeteet/Collaboration-1#2]
@lpeteet       Change the background color of the page

**Comment by lpeteet** [comment]
OK, Will do!  I will advise when done and close Issue #2.

**Comment by lpeteet** [comment]
Modified Style.css to have the Body use a new image file "concrete_seamless.png" for the background.
Closing this issue!

**Comment by MelanieWest** [comment]
Thanks! See you in the morning.

MW


Sent from Mail for Windows 10
